<!--
language grammars reference document: https://manual.macromates.com/en/language_grammars
You can  add your language directly in  this file
-->
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>txt.output.microbit</string>
        <key>name</key>
        <string>output-microbit</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Starting\]|\[Info\]|\[Démarrage\])(.*)</string>
                <key>name</key>
                <string>output-microbit.start</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Done\]|\[Fait\])(.+)</string>
                <key>name</key>
                <string>output-microbit.done</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Error\]|\[Erreur\]|-------> )(.+)</string>
                <key>name</key>
                <string>output-microbit.error</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>token.warning-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\[Warning\]|\[Avertissement\])(.+)</string>
                <key>name</key>
                <string>output-microbit.warning</string>
            </dict>
        </array>
    </dict>
</plist>